---
languages:
  javascript:
    enabled: true
  css:
    enabled: false
  python:
    enabled: false
tools:
  - eslint@9.3.0
exclude_paths:
  - ".bundle/**"
  - "spec/**/*"
  - "benchmarks/**/*"
  - "**.min.js"
  - "**/tests/**"
  - ".github/workflows/**" # Exclude GitHub workflows